# Generated by Django 4.2.10 on 2024-02-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('BCA', 'BCA'), ('BBA', 'BBA'), ('iMCA', 'iMCA'), ('MBA', 'MBA'), ('MCA', 'MCA')], default='Select Your Branch', max_length=5),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], default='Select Your Gender', max_length=6),
        ),
    ]
