# Generated by Django 4.2.10 on 2024-03-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_branch_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('BBA', 'BBA'), ('MCA', 'MCA'), ('MBA', 'MBA'), ('iMCA', 'iMCA'), ('BCA', 'BCA')], default='Select Your Branch', max_length=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
