# Generated by Django 4.2.10 on 2024-03-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_branch_alter_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('MCA', 'MCA'), ('BCA', 'BCA'), ('BBA', 'BBA'), ('MBA', 'MBA'), ('iMCA', 'iMCA')], default='Select Your Branch', max_length=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Select Your Gender', max_length=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
