# Generated by Django 4.2.10 on 2024-03-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_branch_alter_student_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('iMCA', 'iMCA'), ('MBA', 'MBA'), ('MCA', 'MCA'), ('BBA', 'BBA'), ('BCA', 'BCA')], default='Select Your Branch', max_length=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], default='Select Your Gender', max_length=6),
        ),
    ]
