# Generated by Django 4.2.10 on 2024-03-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_branch_alter_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('BBA', 'BBA'), ('iMCA', 'iMCA'), ('MBA', 'MBA'), ('BCA', 'BCA'), ('MCA', 'MCA')], default='Select Your Branch', max_length=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Select Your Gender', max_length=6),
        ),
    ]
