# Generated by Django 4.2.10 on 2024-03-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_student_branch_alter_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('MBA', 'MBA'), ('BBA', 'BBA'), ('iMCA', 'iMCA'), ('BCA', 'BCA'), ('MCA', 'MCA')], default='Select Your Branch', max_length=5),
        ),
    ]
