# Generated by Django 4.2.10 on 2024-03-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_student_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('MCA', 'MCA'), ('BCA', 'BCA'), ('MBA', 'MBA'), ('BBA', 'BBA'), ('iMCA', 'iMCA')], default='Select Your Branch', max_length=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], default='Select Your Gender', max_length=6),
        ),
    ]
