# Generated by Django 4.2.10 on 2024-03-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_student_branch_alter_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('BCA', 'BCA'), ('MBA', 'MBA'), ('iMCA', 'iMCA'), ('MCA', 'MCA'), ('BBA', 'BBA')], default='Select Your Branch', max_length=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Select Your Gender', max_length=6),
        ),
    ]
