# Generated by Django 4.2.10 on 2024-02-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('iMCA', 'iMCA'), ('BCA', 'BCA'), ('BBA', 'BBA'), ('MCA', 'MCA'), ('MBA', 'MBA')], default='Select Your Branch', max_length=5),
        ),
    ]
