# Generated by Django 4.2.10 on 2024-02-28 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0002_alter_student_branch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
