# Generated by Django 4.2.10 on 2024-03-04 17:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0005_alter_student_branch_alter_student_gender'),
        ('librarian', '0003_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('bookId', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=25)),
                ('publisher', models.CharField(max_length=25)),
                ('edition', models.IntegerField()),
                ('category', models.CharField(choices=[('CS', 'Computer Science'), ('JN', 'Journal'), ('MG', 'Management'), ('DB', 'Database')], default='Select the Category', max_length=5)),
                ('Price', models.FloatField()),
                ('PubYear', models.IntegerField()),
                ('totAvail', models.IntegerField()),
                ('totIssued', models.IntegerField()),
                ('totQuant', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('issueId', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('issueDate', models.DateField(default=datetime.date.today)),
                ('returnDate', models.DateField(null=True)),
                ('panelty', models.IntegerField(default=0, max_length=4)),
                ('completed', models.BooleanField(default=False)),
                ('BookId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librarian.books')),
                ('StudentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
