# Generated by Django 4.2.10 on 2024-03-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0005_alter_books_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='name',
            new_name='bName',
        ),
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.CharField(choices=[('MG', 'Management'), ('CS', 'Computer Science'), ('JN', 'Journal'), ('DB', 'Database')], default='Select the Category', max_length=5),
        ),
    ]
