# Generated by Django 4.2.10 on 2024-03-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0007_alter_books_bname_alter_books_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.CharField(choices=[('JN', 'Journal'), ('CS', 'Computer Science'), ('DB', 'Database'), ('MG', 'Management')], default='Select the Category', max_length=5),
        ),
    ]
