# Generated by Django 4.2.10 on 2024-03-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0008_alter_books_author_alter_books_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.CharField(choices=[('Computer Science', 'Computer Science'), ('Management', 'Management'), ('Journal', 'Journal'), ('Database', 'Database')], default='Select the Category', max_length=20),
        ),
        migrations.AlterField(
            model_name='issues',
            name='panelty',
            field=models.IntegerField(default=0),
        ),
    ]
